### ISSUE TITLE
seafile-admin start --fastcgi not working from bash/sh

### ISSUE THREAD

**Issue by bhughes339** [VGoshev/seafile-docker#4]
When attempting to run `seafile-admin start --fastcgi` from bash/sh (from the container or using `docker exec`), I'm receiving the following error:
```
~ $ seafile-admin start --fastcgi

Starting seafile-server...
Starting seahub in fastcgi mode...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/seafile/seafile-server/seahub/seahub/__init__.py", line 3, in <module>
    from handlers import repo_created_cb, repo_deleted_cb
  File "/home/seafile/seafile-server/seahub/seahub/handlers.py", line 4, in <module>
    import settings
  File "/home/seafile/seafile-server/seahub/seahub/settings.py", line 9, in <module>
    from seaserv import FILE_SERVER_ROOT, FILE_SERVER_PORT, SERVICE_URL
ImportError: No module named seaserv
Error: Failed to start seahub in fastcgi mode
```

The command works fine when used in the `docker_run` code.

EDIT: looks like the python modules aren't being sourced into the shell properly. The following bash script ran the fastcgi server correctly:
```
#!/bin/sh
source /etc/profile.d/python-local.sh
seafile-admin start --fastcgi
```

**Comment by VGoshev** [comment]
Yeah, you need to add sove env variables, I'll update readme and add some helper script, thanks for report
